# Script generated by ChatGPT
#!/bin/bash

# Install npm packages
echo "Installing npm packages..."
npm install

# Reset the database and run migrations, also creating admin user
echo "Resetting database and running migrations..."
npx prisma migrate reset --force

# Check that the required compilers/interpreters are installed
echo "Verifying installations..."
gcc --version
g++ --version
python3 --version
java -version

echo "All required compilers/interpreters are installed."

echo "Setup complete."
